[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node scripts/start.mjs"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
